export { default as LatestNotices } from './latestNotices.vue'
export { default as LatestDynamics } from './latestDynamics.vue'
export { default as LatestResearch } from './latestResearch.vue'
export { default as QuickShortcuts } from './quickShortcuts.vue'
export { default as WelcomeSection } from './welcomeSection.vue'
